import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';

export const THEME = {
  light: {
    background: 'hsl(0 0% 100%)',
    foreground: 'hsl(0 0% 0%)',
    card: 'hsl(0 0% 100%)',
    cardForeground: 'hsl(0 0% 0%)',
    popover: 'hsl(0 0% 100%)',
    popoverForeground: 'hsl(0 0% 0%)',
    primary: 'hsl(0 0% 0%)',
    primaryForeground: 'hsl(0 0% 100%)',
    secondary: 'hsl(0 0% 96%)',
    secondaryForeground: 'hsl(0 0% 0%)',
    muted: 'hsl(0 0% 96%)',
    mutedForeground: 'hsl(0 0% 45%)',
    accent: 'hsl(0 0% 96%)',
    accentForeground: 'hsl(0 0% 0%)',
    destructive: 'hsl(0 84% 60%)',
    border: 'hsl(0 0% 90%)',
    input: 'hsl(0 0% 90%)',
    ring: 'hsl(0 0% 0%)',
    radius: '0.5rem',
    chart1: 'hsl(12 76% 61%)',
    chart2: 'hsl(173 58% 39%)',
    chart3: 'hsl(197 37% 24%)',
    chart4: 'hsl(43 74% 66%)',
    chart5: 'hsl(27 87% 67%)',
  },
  dark: {
    background: 'hsl(0 0% 0%)',
    foreground: 'hsl(0 0% 100%)',
    card: 'hsl(0 0% 0%)',
    cardForeground: 'hsl(0 0% 100%)',
    popover: 'hsl(0 0% 0%)',
    popoverForeground: 'hsl(0 0% 100%)',
    primary: 'hsl(0 0% 100%)',
    primaryForeground: 'hsl(0 0% 0%)',
    secondary: 'hsl(0 0% 10%)',
    secondaryForeground: 'hsl(0 0% 100%)',
    muted: 'hsl(0 0% 10%)',
    mutedForeground: 'hsl(0 0% 63%)',
    accent: 'hsl(0 0% 10%)',
    accentForeground: 'hsl(0 0% 100%)',
    destructive: 'hsl(0 62% 55%)',
    border: 'hsl(0 0% 15%)',
    input: 'hsl(0 0% 15%)',
    ring: 'hsl(0 0% 100%)',
    radius: '0.5rem',
    chart1: 'hsl(220 70% 50%)',
    chart2: 'hsl(160 60% 45%)',
    chart3: 'hsl(30 80% 55%)',
    chart4: 'hsl(280 65% 60%)',
    chart5: 'hsl(340 75% 55%)',
  },
} as const;

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
